services:
    updater:
        build: .
        restart: unless-stopped
        ports:
            - "${PORT}:${PORT}"
        environment:
            - WEBHOOK_SECRET=${WEBHOOK_SECRET}
            - PORT=${PORT}
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /home/containers:/home/containers
        working_dir: /app
